### ISSUE TITLE
Plugin "Mi Vacuum Cleaner Gen1"

### ISSUE THREAD

**Issue by Nodiink** [MishFdM/Mi_Home_ITA#35]
Nella pagina per gestire la programmazione per dispositivo (voce menu: "Pianifica pulizioa > Aggiungi tempo") la label "conferma" in alto a dx va a capo. Suggerirei qualcosa di più breve, tipo "OK"

![screenshot_2017-12-12-12-01-35-607_com xiaomi smarthome](https://user-images.githubusercontent.com/10235999/33883506-5033ed48-df3c-11e7-81a5-e176be1fc258.png)

Nella pagina "Pacchetto vocale" nel pacchetto in uso si legge "(difetto)": che significa?

![screenshot_2017-12-12-12-02-29-913_com xiaomi smarthome](https://user-images.githubusercontent.com/10235999/33883716-2360a468-df3d-11e7-8900-27cde71647f4.png)

**Comment by ghost** [comment]
Corretti https://github.com/MishFdM/Mi_Home_ITA/pull/36
