### ISSUE TITLE
Xiaomi Dafag Smart camera plugin

### ISSUE THREAD

**Issue by eih64** [MishFdM/Mi_Home_ITA#49]
Prima segnalazione:
![1](https://user-images.githubusercontent.com/35448702/34934448-68d7e498-f9d2-11e7-92c3-16de32f198fe.PNG)
Risoluzione bassa

**Comment by eih64** [comment]
E' il mio primo plugin, quindi non so fino a che punto spingermi nei tuoi confronti.
Sentiti libero di bloccarmi ogni volta lo riterrari opportuno su richieste che vanno oltre i limiti.
Linee sovrapposte.
![screenshot_20180115-083827](https://user-images.githubusercontent.com/35448702/34935042-6ceeee58-f9d4-11e7-890b-98c1093134cf.jpg)

**Comment by ghost** [comment]
Puoi spingerti fin dove vuoi, basta che aggiungi le ulteriori segnalazioni in una sola issue, sennò si crea troppa confusione.

**Comment by eih64** [comment]
Si può diminuire dimensione del testo?
OK 
![screenshot_20180115-170248-1](https://user-images.githubusercontent.com/35448702/34951364-f5a25dc8-fa0d-11e7-8c04-5ff63bf204bb.jpg)

**Comment by eih64** [comment]
Continuerò ad aggiungere in questa issue . Grazie e scusa la doppia apertura ..

**Comment by ghost** [comment]
Penso che quei caratteri Cinesi in alto al nome della videocamera, siano proprio il nome della videocamera.

Quindi nessuna traduzione per quello.

**Comment by ale8530** [comment]
Su richiesta di orlaf
