### ISSUE TITLE
Xiaomi Dafag Smart camera plugin

### ISSUE THREAD

**Issue by eih64** [MishFdM/Mi_Home_ITA#50]
Aperta era aperta, forse me la sono chiusa da solo (erroneamente).
Lasciamo perdere  ...

![1](https://user-images.githubusercontent.com/35448702/34948152-41f298aa-fa04-11e7-8d2b-da59e526fdbf.PNG)
![screenshot_20180115-083827](https://user-images.githubusercontent.com/35448702/34948154-4214478e-fa04-11e7-9ef2-3716ef61ab1f.jpg)

Modalità a basso consumo
Sovrapposizione di linee

Riporto integralmente quanto osservo. Poi se fattibile o meno lo decidete voi
Saluti
eih64

**Comment by ghost** [comment]
Fattibilissimo, ma le scritte in cinese dove sono?

**Comment by eih64** [comment]
Rintraccio e giro dove osservo scritte in cinese.
![2](https://user-images.githubusercontent.com/35448702/34951609-c4012096-fa0e-11e7-8fef-66efc2688f0c.PNG)

Da adesso in poi scrivo solo su una delle 2 issues.

**Comment by ghost** [comment]
Scitta Cinese server-side, ma non vorrei essere troppo precipitoso. Poi verifico...

**Comment by ghost** [comment]
Ah...tutto il resto è stato fixato.

**Comment by ale8530** [comment]
Su richiesta di orlaf
