### ISSUE TITLE
Dafag camera

### ISSUE THREAD

**Issue by eih64** [MishFdM/Mi_Home_ITA#58]
Allego file. Saluti

![17 01 2018](https://user-images.githubusercontent.com/35448702/35064817-27806d42-fbc3-11e7-8d6b-af3082f96abb.jpg)
![17 01 2018_1](https://user-images.githubusercontent.com/35448702/35064818-27a1c744-fbc3-11e7-88b5-f18cb0e4f5aa.jpg)

**Comment by ghost** [comment]
Fixati

https://github.com/MishFdM/Mi_Home_ITA/pull/59/commits/2353e6c1229a440164337e76a3b666a5f1a289d8

Puoi chiudere issue in attesa del prossimo pacchetto
