### ISSUE TITLE
Xiaomi Dafag intelligente plugin di fotocamera 

### ISSUE THREAD

**Issue by eih64** [MishFdM/Mi_Home_ITA#61]
![screenshot_20180118-070049](https://user-images.githubusercontent.com/35448702/35089677-900e0f88-fc2f-11e7-95e4-a060f1a1210e.jpg)

Saluti

**Comment by ghost** [comment]
Bug del plugin al momento non fixabile.

Vedremo con le prossime versioni.

**Comment by eih64** [comment]
Forse questo è già fissato.
Non sono + scaricabili i plugins (manca il link)
Saluti

![17 01 2018_1](https://user-images.githubusercontent.com/35448702/35141512-0ad187f4-fcf3-11e7-9735-7deb3159e8ff.jpg)

**Comment by ghost** [comment]
Tutti fixati, se il link manca è perché lo sto attendendo dai gestori del blog.
